const JuzNames = [
    { number: 1, name: "الم" },
    { number: 2, name: "سَیَقُولُ" },
    { number: 3, name: "تِلْكَ الرُّسُلُ" },
    { number: 4, name: "لَن تَنَالُوا" },
    { number: 5, name: "وَالْمُحْصَنَاتُ" },
    { number: 6, name: "لَا یُحِبُّ اللّٰہُ" },
    { number: 7, name: "وَاذَا سَمِعُوا" },
    { number: 8, name: "وَلَوْ اَنَّنَا" },
    { number: 9, name: "قَالَ الْمَلَاُ" },
    { number: 10, name: "وَاعْلَمُوْا" },
    { number: 11, name: "یَعْتَذِرُوْنَ" },
    { number: 12, name: "وَمَا مِنْ دَآبَّۃٍ" },
    { number: 13, name: "وَمَآ اُبَرِّءُ" },
    { number: 14, name: "رُبَمَا" },
    { number: 15, name: "سُبْحَانَ الَّذِی" },
    { number: 16, name: "قَالَ اَلْمَ" },
    { number: 17, name: "اقْتَرَبَ" },
    { number: 18, name: "قَدْ اَفْلَحَ" },
    { number: 19, name: "وَقَالَ الَّذِیْنَ" },
    { number: 20, name: "اَمَّنْ خَلَقَ" },
    { number: 21, name: "اُتْلُ مَآ اُوْحِیَ" },
    { number: 22, name: "وَمَن یَّقْنُتْ" },
    { number: 23, name: "وَمَا لِیَ" },
    { number: 24, name: "فَمَنْ اَظْلَمُ" },
    { number: 25, name: "اِلَیۡہِ یُرَدُّ" },
    { number: 26, name: "حَمٓ" },
    { number: 27, name: "قَالَ فَمَا خَطْبُكُمْ" },
    { number: 28, name: "قَدْ سَمِعَ اللّٰہُ" },
    { number: 29, name: "تَبَارَکَ الَّذِی" },
    { number: 30, name: "عَمْ یَتَسَآءَلُوْنَ" },
  ];
  export default JuzNames
  